export const defaultUsers = [
  {
    id: 'usr-001',
    name: 'Cap. J. Rodriguez',
    email: 'analista@kle.local',
    passwordHash: '0ead2060b65992dca4769af601a1b3a35ef38cfad2c2c465bb160ea764157c5d',
    role: 'analista',
  },
  {
    id: 'usr-002',
    name: 'Autoridad Apoyada',
    email: 'autoridad@kle.local',
    passwordHash: '0ead2060b65992dca4769af601a1b3a35ef38cfad2c2c465bb160ea764157c5d',
    role: 'autoridad',
  },
];

export const defaultAuthorityData = {
  requests: [
    {
      id: 'req-001',
      title: 'Actualización de comportamiento de Ahmed Al-Rashidi',
      description: 'Revisar cambios observados tras las dos últimas reuniones y actualizar riesgos de comunicación.',
      objectiveId: 'obj-001',
      priority: 'high',
      dueDate: '2026-07-05',
      type: 'behavior-update',
      status: 'review',
      createdAt: '2026-06-14T08:00:00Z',
      updatedAt: '2026-06-15T10:30:00Z',
      analystName: 'Analista Demo',
      analystResponse: 'Se ha revisado el perfil conductual y se han actualizado los riesgos de comunicación pendientes de validación final.',
    },
    {
      id: 'req-002',
      title: 'Dossier completo de Ibrahim Diouf',
      description: 'Necesitamos una visión integral previa a la próxima visita técnica programada.',
      objectiveId: 'obj-003',
      priority: 'critical',
      dueDate: '2026-06-30',
      type: 'full-dossier',
      status: 'drafting',
      createdAt: '2026-06-18T10:30:00Z',
      updatedAt: '2026-06-21T09:00:00Z',
      analystName: 'Analista Demo',
      analystResponse: 'Dossier en elaboración con foco en contexto relacional, intereses y últimas interacciones.',
    },
    {
      id: 'req-003',
      title: 'Actualización sociocultural de Fatima Benkhouya',
      description: 'Incluir nuevos contactos institucionales y recomendaciones protocolarias para foro multilateral.',
      objectiveId: 'obj-002',
      priority: 'medium',
      dueDate: '2026-07-12',
      type: 'sociocultural-update',
      status: 'pending',
      createdAt: '2026-06-20T09:15:00Z',
    },
  ],
  evaluations: [
    {
      id: 'eval-001',
      objectiveId: 'obj-001',
      date: '2026-05-15',
      location: 'Embajada de España en Maravia',
      strategyFit: 8,
      trustAndCommunication: 8,
      objectiveProgress: 7,
      objectionHandling: 7,
      nextStepsClarity: 8,
      difficulties: 'La principal barrera fue el tiempo limitado disponible durante la reunión.',
      opportunities: 'Alta receptividad a una visita técnica y buena disposición a la cooperación bilateral.',
      futureChanges: 'Preparar con mayor antelación documentación técnica resumida y reforzar el seguimiento previo.',
      otherRelevantAspects: 'Buena sintonía personal y conveniencia de mantener seguimiento trimestral.',
      createdAt: '2026-05-15T19:10:00Z',
    },
    {
      id: 'eval-002',
      objectiveId: 'obj-005',
      date: '2026-06-01',
      location: 'Cámara de Comercio de Madrid',
      strategyFit: 9,
      trustAndCommunication: 9,
      objectiveProgress: 8,
      objectionHandling: 8,
      nextStepsClarity: 9,
      difficulties: 'No surgieron resistencias relevantes, aunque hubo que concretar mejor el alcance temporal.',
      opportunities: 'Interés claro en energías renovables y desarrollo portuario; oportunidad de seguimiento económico.',
      futureChanges: 'Llevar propuestas aún más ejecutivas y coordinadas con actores económicos institucionales.',
      otherRelevantAspects: 'Solicita dossier adicional y conviene coordinar con ICEX.',
      createdAt: '2026-06-01T13:30:00Z',
    },
  ],
  publishedProfiles: [],
  sharedDocuments: [],
  dossierEvaluations: [
    {
      id: 'dossier-eval-001',
      objectiveId: 'obj-001',
      date: '2026-05-14',
      location: 'Embajada de España en Maravia',
      profileUsefulness: 9,
      structureClarity: 8,
      psychologicalAdvantage: 8,
      biographyDepth: 7,
      behaviorGuidance: 8,
      conversationTopics: 9,
      socioculturalFramework: 8,
      geopoliticalAccuracy: 7,
      precisionAndReliability: 8,
      detailLevel: 8,
      additionalInformationNeeded: 'Habría sido útil contar con escenarios de reacción probables ante objeciones técnicas y una guía de prioridades de cierre.',
      contentChanges: 'Reduciría algo la parte descriptiva inicial y pondría antes los mensajes clave, riesgos y recomendaciones accionables.',
      otherRelevantAspects: 'El dosier fue especialmente útil para preparar la aproximación y orientar bien el tono del encuentro.',
      globalContribution: 'Buena',
      createdAt: '2026-05-16T08:15:00Z',
    },
  ],
  observationQuestionnaires: [
    {
      id: 'obs-001',
      objectiveId: 'obj-001',
      date: '2026-05-15',
      context: 'Reunión bilateral en entorno protocolario con presencia de dos asesores técnicos.',
      positiveIndicators: 'Actitud abierta, escucha activa y buena disposición a continuar el contacto técnico.',
      alertIndicators: 'Sensibilidad ante cuestiones de plazos y necesidad de concretar mejor los retornos esperados.',
      recommendations: 'Mantener enfoque directo, documentación muy sintética y cierre con siguientes pasos definidos.',
      createdAt: '2026-05-15T18:40:00Z',
      observerName: 'Cnel. Ruiz',
      observerRankRole: 'Agregado de Defensa, Ejército de Tierra',
      startTimeDuration: '10:00 - 11:30 (90 min)',
      cityLocation: 'Embajada de España, Maravia',
      interactionReason: 'Reunión bilateral de seguimiento',
      interactionLanguage: 'Español',
      targetOtherLanguages: 'Inglés (alto), Francés (medio)',
      usedInterpreters: 'no',
      companions: [
        { name: 'Tte. Coronel Martínez', rankArmy: 'Jefe de Sección, Ejército del Aire' },
      ],
      previousInteractions: [
        { date: '2026-03-12', location: 'Ministerio de Defensa', reason: 'Presentación de credenciales' },
      ],
      qGeneral: [
        'Persona muy expresiva y abierta, mantiene contacto físico natural.',
        'Habla pausada y clara, tono medio. Gesticula moderadamente al enfatizar puntos clave.',
        'Se rige principalmente por la planificación y la razón, muy estructurado.',
        'Sí, complexión atlética.',
        'No se percibió ninguna dificultad física.',
        'Uniforme de gala impecable, limpio y ordenado.',
        'Traje formal en reuniones no oficiales.',
        'No tomó notas él mismo; delegó en sus asesores.',
      ],
      qInteraction: [
        'Trato muy cordial y respetuoso, pero exigente en los detalles técnicos.',
        'Saludo formal con mano tendida, firme y prolongado. Trato similar a toda la comitiva.',
        'Persona muy culta. Habló de geopolítica regional, historia local y aficiones deportivas.',
        'Mostró gusto por la comida local tradicional, prefiere platos especiados.',
        'Aficionado a la equitación y la lectura histórica militar.',
        'Relación formal y respetuosa con su cónyuge; trato profesional con otras mujeres.',
        'Mencionó de forma anecdótica su paso por la academia militar en España.',
        'Muestra gran respeto por las tradiciones españolas y conoce bien el idioma.',
      ],
      qTeam: [
        'Trato correcto y jerárquico pero cercano. Se dirigió por su empleo al Capitán López.',
        'Mayor afinidad con el Tte. Coronel Benítez (asesor jurídico). Menor interacción con el secretario.',
        'Complicidad técnica alta en la validación de plazos con su asesor económico.',
        'El Tte. Coronel Benítez actúa como líder de staff en su ausencia.',
        'Equipo muy cohesionado y de alta preparación profesional.',
      ],
      qPersonality: [
        true, false, true, true, false, false, false, false, false, false,
        false, false, false, false, true, false, true, false, false, true,
        false, false, true, true, false, false, true, false, true, false,
      ],
      qBehaviors: [
        true, false, true, true, false, false, false, false, false, true,
        false, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false, false, false, false, false,
        true, false, false, false, false, false, false, false, false, false,
        false, false, false, false, false, false,
      ],
    },
  ],
};
